/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "calculadora.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <pthread.h>
#include <semaphore.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif


long compartilhada = 0;//memoria compartilhada
sem_t mutex; //declaração

//Funcao que vai executar a soma de maneira paralelizada
void *sumThread(void *arg) {
    sem_wait(&mutex); //entra na sessão crítica

	sem_post(&mutex); //sai da sessão crítica
}

//Funcao que vai executar a subtracao de maneira paralelizada
void *subThread(void *arg) {}

//Funcao que vai executar a multiplicacao de maneira paralelizada
void *multThread(void *arg) {}

//Funcao que vai executar a divisao de maneira paralelizada
void *divThread(void *arg) {}

static void
somasub_prog_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	pthread_t tid;
    int ret;

	sem_init(&mutex, 0, 1); 
	//segundo arg: 0 - semaforo compartilhado entre threads 
	//terceiro arg: 1 - valor inicial do semaforo
	ret = pthread_create(&tid, NULL, sumThread, NULL)
	union {
		operandos soma_1_arg;
		operandos sub_1_arg;
		operandos divisao_1_arg;
		operandos mult_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case SOMA:
		_xdr_argument = (xdrproc_t) xdr_operandos;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) soma_1_svc;
		break;

	case SUB:
		_xdr_argument = (xdrproc_t) xdr_operandos;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) sub_1_svc;
		break;

	case DIVISAO:
		_xdr_argument = (xdrproc_t) xdr_operandos;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) divisao_1_svc;
		break;

	case MULT:
		_xdr_argument = (xdrproc_t) xdr_operandos;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) mult_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	pmap_unset (SOMASUB_PROG, SOMASUB_VERSION);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, SOMASUB_PROG, SOMASUB_VERSION, somasub_prog_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (SOMASUB_PROG, SOMASUB_VERSION, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, SOMASUB_PROG, SOMASUB_VERSION, somasub_prog_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (SOMASUB_PROG, SOMASUB_VERSION, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
