/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CALCULADORA_H_RPCGEN
#define _CALCULADORA_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct operandos {
	int a;
	int b;
};
typedef struct operandos operandos;

#define SOMASUB_PROG 0x20000001
#define SOMASUB_VERSION 1

#if defined(__STDC__) || defined(__cplusplus)
#define SOMA 1
extern  int * soma_1(operandos *, CLIENT *);
extern  int * soma_1_svc(operandos *, struct svc_req *);
#define SUB 2
extern  int * sub_1(operandos *, CLIENT *);
extern  int * sub_1_svc(operandos *, struct svc_req *);
#define DIVISAO 3
extern  int * divisao_1(operandos *, CLIENT *);
extern  int * divisao_1_svc(operandos *, struct svc_req *);
#define MULT 4
extern  int * mult_1(operandos *, CLIENT *);
extern  int * mult_1_svc(operandos *, struct svc_req *);
extern int somasub_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define SOMA 1
extern  int * soma_1();
extern  int * soma_1_svc();
#define SUB 2
extern  int * sub_1();
extern  int * sub_1_svc();
#define DIVISAO 3
extern  int * divisao_1();
extern  int * divisao_1_svc();
#define MULT 4
extern  int * mult_1();
extern  int * mult_1_svc();
extern int somasub_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_operandos (XDR *, operandos*);

#else /* K&R C */
extern bool_t xdr_operandos ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CALCULADORA_H_RPCGEN */
