/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include <stdio.h>
#include "calculadora.h"

int *
soma_1_svc (operandos *argp, struct svc_req *rqstp)
{
	static int  result;
	int count = 0;

	while(1) {}
	printf("Recebi um chamado: soma %d %d\n", argp->a, argp->b);
	result = argp->a + argp->b;

	return &result;
}

int *
sub_1_svc(operandos *argp, struct svc_req *rqstp)
{
	static int  result;

	printf("Recebi um chamado: sub %d %d\n", argp->a, argp->b);
	result = argp->a - argp->b;

	return &result;
}

int *
mult_1_svc (operandos *argp, struct svc_req *rqstp)
{
	static int  result;

	printf("Recebi um chamado: mult %d %d\n", argp->a, argp->b);
	result = argp->a * argp->b;

	return &result;
}

int *
divisao_1_svc(operandos *argp, struct svc_req *rqstp)
{
	static int  result;

	printf("Recebi um chamado: div %d %d\n", argp->a, argp->b);
	result = argp->a / argp->b;

	return &result;
}
