/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "operation.h"

int 
options (operandos *op) {
	int choice;
    printf("\n\n");
    printf("***** Choose an option ******\n");
    printf("(1). Sum two numbers\n");
    printf("(2). Subtract two numbers \n");
    printf("(3). Divide two numbers\n");
    printf("(4). Multiply two numbers\n");
    printf("(5). Quit\n");
    printf("*****************************\n");
    
	printf("Type an option => \t");
	scanf("%d",&choice);
	if(choice < 5) {
		printf("\nFirst number =>\t");
		scanf("%d", &op->a);
		printf("Second number =>\t");
		scanf("%d", &op->b);
	}

	return choice;
}

void 
operation_prog_1(char *host) {
	CLIENT *clnt;
	enum clnt_stat retval_1;
	int result_1;
	operandos soma_1_arg;
	enum clnt_stat retval_2;
	int result_2;
	operandos sub_1_arg;
	enum clnt_stat retval_3;
	int result_3;
	operandos divisao_1_arg;
	enum clnt_stat retval_4;
	int result_4;
	operandos mult_1_arg;
	int result;
	operandos op_arg;

	//switch case choice:
	int choice, fstNumber, sndNumber;

#ifndef DEBUG
	clnt = clnt_create(host, OPERATION_PROG, OPERATION_VERSION, "udp");
	if (clnt == NULL)
	{
		clnt_pcreateerror(host);
		exit(1);
	}
#endif /* DEBUG */

	while (1) {
		choice = options(&op_arg);
		switch (choice) {
		case 1:
			retval_1 = soma_1(&op_arg, &result, clnt);
			if (retval_1 != RPC_SUCCESS)
			{
				clnt_perror(clnt, "call failed");
			}
			printf("%d + %d = %d",op_arg.a,op_arg.b,result);

			break;

		case 2:
			retval_2 = sub_1(&op_arg, &result, clnt);
			if (retval_2 != RPC_SUCCESS)
			{
				clnt_perror(clnt, "call failed");
			}
			printf("%d - %d = %d",op_arg.a,op_arg.b,result);

			break;

		case 3:
			retval_3 = divisao_1(&op_arg, &result, clnt);
			if (retval_3 != RPC_SUCCESS)
			{
				clnt_perror(clnt, "call failed");
			}
			printf("%d / %d = %d",op_arg.a,op_arg.b,result);

			break;

		case 4:
			retval_4 = mult_1(&op_arg, &result, clnt);
			if (retval_4 != RPC_SUCCESS)
			{
				clnt_perror(clnt, "call failed");
			}
			printf("%d * %d = %d",op_arg.a,op_arg.b,result);

			break;

		case 5:
            printf("See you later!\n");
            exit(0);

		default:
			printf("Command invalid.");
			break;
		}
	}

#ifndef DEBUG
	clnt_destroy(clnt);
#endif /* DEBUG */
}

int 
main(int argc, char *argv[]) {
	char *host;

	if (argc < 2) {
		printf("usage: %s server_host\n", argv[0]);
		exit(1);
	}

	host = argv[1];
	operation_prog_1(host);
	exit(0);
}

